import React, { useEffect, useMemo } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Customer } from "@/types";
import { saveCustomer } from "@/integrations/supabase/repositories/customerRepository";
import { useAuth } from "@/context/AuthContext";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";

const formSchema = z.object({
  name: z.string().min(1, "Nazwa jest wymagana"),
  taxId: z.string().min(10, "NIP jest wymagany i musi mieć 10 cyfr").max(10, "NIP musi mieć 10 cyfr"),
  address: z.string().min(1, "Adres jest wymagany"),
  postalCode: z.string().min(1, "Kod pocztowy jest wymagany"),
  city: z.string().min(1, "Miasto jest wymagane"),
  email: z.string().email("Niepoprawny format email").optional().or(z.literal("")),
  phone: z.string().optional(),
  customerType: z.enum(['odbiorca', 'sprzedawca', 'both'], { required_error: "Typ klienta jest wymagany" }),
});

interface CustomerFormProps {
  initialData?: Customer;
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (customer: Customer) => void;
  defaultCustomerType?: 'odbiorca' | 'sprzedawca';
}

const CustomerForm = ({
  initialData,
  isOpen,
  onClose,
  onSuccess,
  defaultCustomerType,
}: CustomerFormProps) => {
  const { user } = useAuth();
  const isEditing = !!initialData?.id;

  const storageKey = useMemo(() => {
    const userId = user?.id ?? 'anonymous';
    return `customer_form_draft:${userId}:${isEditing ? (initialData?.id ?? 'edit') : 'new'}`;
  }, [user?.id, isEditing, initialData?.id]);

  const defaultValues = useMemo(
    () => ({
      name: initialData?.name || "",
      taxId: initialData?.taxId || "",
      address: initialData?.address || "",
      postalCode: initialData?.postalCode || "",
      city: initialData?.city || "",
      email: initialData?.email || "",
      phone: initialData?.phone || "",
      customerType: initialData?.customerType || defaultCustomerType || 'odbiorca',
    }),
    [
      initialData?.name,
      initialData?.taxId,
      initialData?.address,
      initialData?.postalCode,
      initialData?.city,
      initialData?.email,
      initialData?.phone,
      initialData?.customerType,
      defaultCustomerType,
    ]
  );

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues,
  });

  useEffect(() => {
    if (!isOpen) return;
    if (isEditing) return;
    try {
      const raw = localStorage.getItem(storageKey);
      if (!raw) return;
      const parsed = JSON.parse(raw);
      if (!parsed || typeof parsed !== 'object') return;
      form.reset({ ...defaultValues, ...parsed });
    } catch {
      // ignore
    }
  }, [isOpen, isEditing, storageKey, form, defaultValues]);

  useEffect(() => {
    if (!isOpen) return;
    if (isEditing) return;
    const sub = form.watch((values) => {
      try {
        localStorage.setItem(storageKey, JSON.stringify(values));
      } catch {
        // ignore
      }
    });
    return () => sub.unsubscribe();
  }, [form, isOpen, isEditing, storageKey]);

  const handleCancel = () => {
    if (!isEditing) {
      try {
        localStorage.removeItem(storageKey);
      } catch {
        // ignore
      }
    }
    onClose();
  };

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    try {
      // Ensure all required fields are present by providing defaults if needed
      if (!user?.id) {
        toast.error("Brak informacji o użytkowniku. Zaloguj się ponownie.");
        return;
      }
      const customer: Customer = {
        id: initialData?.id || "",  // Will be generated by DB if empty
        name: values.name,          // Required field from form
        taxId: values.taxId || "",  // Optional field
        address: values.address,    // Required field from form
        postalCode: values.postalCode, // Required field from form
        city: values.city,          // Required field from form
        email: values.email || "",  // Optional field
        phone: values.phone || "",  // Optional field
        customerType: values.customerType,
        user_id: user.id, // Enforce RLS: always include user_id
      };

      const savedCustomer = await saveCustomer(customer);
      toast.success(
        isEditing ? "Klient zaktualizowany" : "Klient utworzony"
      );

      if (!isEditing) {
        try {
          localStorage.removeItem(storageKey);
        } catch {
          // ignore
        }
      }

      onSuccess(savedCustomer);
      onClose();
    } catch (error) {
      console.error("Error saving customer:", error);
      toast.error("Wystąpił błąd podczas zapisywania klienta");
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="sm:max-w-[525px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {isEditing ? "Edytuj klienta" : "Dodaj nowego klienta"}
          </DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="space-y-4 pt-2"
          >

<FormField
              control={form.control}
              name="taxId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>NIP</FormLabel>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <FormControl>
                      <Input placeholder="NIP" maxLength={10} {...field} />
                    </FormControl>
                    <Button
                      type="button"
                      size="sm"
                      variant="secondary"
                      style={{ minWidth: 60, padding: '0 10px' }}
                      onClick={async () => {
                        const nip = form.getValues("taxId");
                        if (!nip || nip.length !== 10) {
                          toast.error("Podaj poprawny NIP (10 cyfr)");
                          return;
                        }
                        try {
                          const today = new Date().toISOString().slice(0, 10);
                          const res = await fetch(`https://wl-api.mf.gov.pl/api/search/nip/${nip}?date=${today}`);

                          let found = false;

                          if (res.ok) {
                            const data = await res.json();
                            if (data.result && data.result.subject) {
                              const subject = data.result.subject;
                              form.setValue("name", subject.name || "");
                              form.setValue("address", subject.workingAddress || subject.residenceAddress || "");
                              // Try to extract postal code and city from address
                              if (subject.workingAddress || subject.residenceAddress) {
                                const addr = subject.workingAddress || subject.residenceAddress;
                                const match = addr.match(/(\d{2}-\d{3})\s+(.+)/);
                                if (match) {
                                  form.setValue("postalCode", match[1]);
                                  form.setValue("city", match[2]);
                                }
                              }
                              toast.success("Dane firmy pobrane z GUS");
                              found = true;
                            }
                          }

                          // Second fallback: MojePaństwo KRS API
                          if (!found) {
                            try {
                              const mpRes = await fetch(
                                `https://api-v3.mojepanstwo.pl/dane/krs_podmioty.json?conditions%5Bpubliczny_nip%5D=${nip}&limit=1`
                              );

                              if (mpRes.ok) {
                                const mpJson: any = await mpRes.json();
                                // The response format may include an array under "data" or "Dataobject" depending on API version.
                                const mpItem =
                                  mpJson?.data?.[0]?.data ||
                                  mpJson?.Dataobject?.[0]?.data ||
                                  mpJson?.items?.[0]?.data;

                                if (mpItem) {
                                  form.setValue("name", mpItem.nazwa || mpItem.name || "");

                                  const addressField =
                                    mpItem.adres ||
                                    mpItem.siedziba ||
                                    mpItem.working_address ||
                                    mpItem.residence_address ||
                                    "";

                                  if (addressField) {
                                    form.setValue("address", addressField);
                                    const match = addressField.match(/(\d{2}-\d{3})\s+(.+)/);
                                    if (match) {
                                      form.setValue("postalCode", match[1]);
                                      form.setValue("city", match[2]);
                                    }
                                  }

                                  toast.success("Dane firmy pobrane z KRS (MojePaństwo)");
                                  found = true;
                                }
                              }
                            } catch (mpErr) {
                              console.warn("MojePaństwo request failed", mpErr);
                            }
                          }

                          // Fallback: search in internal database if not found via external APIs
                          if (!found) {
                            const { data: bpData, error: bpError } = await supabase.rpc("find_user_by_tax_id", {
                              tax_id_param: nip,
                            });

                            if (bpError) {
                              console.error("RPC error find_user_by_tax_id:", bpError);
                            }

                            if (bpData && bpData.length > 0) {
                              const bp: any = bpData[0];
                              form.setValue("name", bp.business_name || bp.name || "");
                              if (bp.address) form.setValue("address", bp.address);
                              if (bp.postal_code) form.setValue("postalCode", bp.postal_code);
                              if (bp.city) form.setValue("city", bp.city);
                              toast.success("Dane firmy pobrane z bazy");
                            } else {
                              // If API responded with error earlier, show that; otherwise generic not found
                              if (!res.ok) {
                                const errorData = await res.json().catch(() => null);
                                const errorMessage = errorData?.error ? errorData.error.message : `Błąd HTTP: ${res.status} ${res.statusText}`;
                                toast.error(`Błąd pobierania danych: ${errorMessage}`);
                              } else {
                                toast.error("Nie znaleziono firmy dla podanego NIP");
                              }
                            }
                          }
                        } catch (err: any) {
                          console.error("Error during NIP search:", err);
                          toast.error(`Błąd podczas wyszukiwania danych: ${err.message || err}`);
                        }
                      }}
                    >
                      Szukaj
                    </Button>
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />
            
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Nazwa</FormLabel>
                  <FormControl>
                    <Input placeholder="Nazwa firmy lub imię i nazwisko" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="address"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Adres</FormLabel>
                  <FormControl>
                    <Input placeholder="Adres" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="postalCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Kod pocztowy</FormLabel>
                    <FormControl>
                      <Input placeholder="Kod pocztowy" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="city"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Miasto</FormLabel>
                    <FormControl>
                      <Input placeholder="Miasto" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Email (opcjonalnie)</FormLabel>
                  <FormControl>
                    <Input placeholder="Email" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="phone"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Telefon (opcjonalnie)</FormLabel>
                  <FormControl>
                    <Input placeholder="Telefon" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="customerType"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Typ klienta</FormLabel>
                  <Select value={field.value} onValueChange={field.onChange}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Wybierz typ klienta" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="odbiorca">Odbiorca</SelectItem>
                      <SelectItem value="sprzedawca">Sprzedawca</SelectItem>
                      <SelectItem value="both">Oba</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="flex justify-end gap-2 pt-4">
              <Button type="button" variant="outline" onClick={handleCancel}>
                Anuluj
              </Button>
              <Button type="submit">
                {isEditing ? "Aktualizuj" : "Dodaj klienta"}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};

export default CustomerForm;
